# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/FPGA/VLIW-BEAST/VLIW-BEAST.cache/wt [current_project]
set_property parent.project_path C:/FPGA/VLIW-BEAST/VLIW-BEAST.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/FPGA/VLIW-BEAST/VLIW-BEAST.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/FPGA/VLIW-BEAST/VLIW-BEAST.srcs/programs/program-0.coe
read_verilog -library xil_defaultlib {
  C:/FPGA/VLIW-BEAST/VLIW-BEAST.srcs/sources_1/new/bit_math_unit.v
  C:/FPGA/VLIW-BEAST/VLIW-BEAST.srcs/sources_1/new/dispatcher.v
  C:/FPGA/VLIW-BEAST/VLIW-BEAST.srcs/sources_1/new/dispatcher_delayer.v
  C:/FPGA/VLIW-BEAST/VLIW-BEAST.srcs/sources_1/new/execution_core.v
  C:/FPGA/VLIW-BEAST/VLIW-BEAST.srcs/sources_1/new/led_IO_manager.v
  C:/FPGA/VLIW-BEAST/VLIW-BEAST.srcs/sources_1/new/register_manager.v
  C:/FPGA/VLIW-BEAST/VLIW-BEAST.srcs/sources_1/new/register_value_chooser.v
  C:/FPGA/VLIW-BEAST/VLIW-BEAST.srcs/sources_1/new/single_port_data_manager.v
  C:/FPGA/VLIW-BEAST/VLIW-BEAST.srcs/sources_1/new/cpu_top.v
}
read_ip -quiet C:/FPGA/VLIW-BEAST/VLIW-BEAST.srcs/sources_1/ip/main_memory/main_memory.xci
set_property used_in_implementation false [get_files -all c:/FPGA/VLIW-BEAST/VLIW-BEAST.srcs/sources_1/ip/main_memory/main_memory_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/FPGA/VLIW-BEAST/VLIW-BEAST.srcs/constrs_1/imports/new/constraints.xdc
set_property used_in_implementation false [get_files C:/FPGA/VLIW-BEAST/VLIW-BEAST.srcs/constrs_1/imports/new/constraints.xdc]


synth_design -top cpu_top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cpu_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cpu_top_utilization_synth.rpt -pb cpu_top_utilization_synth.pb"
